CREATE DATABASE MEDIUSSOFTWARE;
USE  MEDIUSSOFTWARE;


CREATE TABLE ENTIDADSEGURIDAD(
IDENTIDAD INT NOT NULL AUTO_INCREMENT,
CODIGOENTIDAD VARCHAR (50) NOT NULL,
NOMBREENTIDAD VARCHAR (150) NOT NULL,
CLASEENTIDAD VARCHAR(50) NOT NULL,
ESTADOENTIDADSEGURIDAD INT NOT NULL,
CONSTRAINT ENTIDADSEGURIDADPK PRIMARY KEY (IDENTIDAD)
);

CREATE TABLE CIUDAD(
IDCIUDAD INT NOT NULL AUTO_INCREMENT,
NUMEROCIUDAD INT NOT NULL,
CIUDADNOMBRE VARCHAR (100) NOT NULL,
CONSTRAINT CIUDADPK PRIMARY KEY (IDCIUDAD)
);


CREATE TABLE CARGO(
IDCARGO INT NOT NULL AUTO_INCREMENT,
NOMBRECARGO VARCHAR(150) NOT NULL,
SALARIOMINIMO DOUBLE NOT NULL,
SALARIOMAXIMO DOUBLE NOT NULL,
ESTADOCARGO INT NOT NULL,
CONSTRAINT CARGOPK PRIMARY KEY (IDCARGO)
);

CREATE TABLE SECCION(
IDSECCION INT NOT NULL AUTO_INCREMENT,
NOMBRESECCION VARCHAR (50) NOT NULL,
CONSTRAINT SECCIONPK PRIMARY KEY (IDSECCION)
);

CREATE TABLE RETENCIONRENTA(
IDRETENCIONRENTA INT NOT NULL AUTO_INCREMENT,
NOMBRERETENCIONRENTA VARCHAR (50) NOT NULL,
TASARETENCIONRENTA DOUBLE NOT NULL ,
UVTRETENCIONRENTA DOUBLE NOT NULL ,
ESTADORETENCIONRENTA INT NOT NULL,
CONSTRAINT RETENCIONRENTAPK PRIMARY KEY (IDRETENCIONRENTA)
);

CREATE TABLE RETENCIONICA(
IDRETENCIONICA INT NOT NULL AUTO_INCREMENT,
NOMBRERETENCIONICA VARCHAR (50) NOT NULL,
TASARETENCIONICA DOUBLE NOT NULL ,
UVTRETENCIONICA DOUBLE NOT NULL ,
ESTADORETENCIONICA INT NOT NULL,
CONSTRAINT RETENCIONICAPK PRIMARY KEY (IDRETENCIONICA)
);

CREATE TABLE RETEIVA(
IDRETEIVA INT NOT NULL AUTO_INCREMENT,
NOMBRERETEIVA VARCHAR (50) NOT NULL,
TASARETEIVA DOUBLE NOT NULL ,
CONSTRAINT RETEIVAPK PRIMARY KEY (IDRETEIVA)
);


CREATE TABLE MARCA(
IDMARCA INT NOT NULL AUTO_INCREMENT,
NOMBREMARCA VARCHAR (50) NOT NULL,
ESTADOMARCA INT NOT NULL,
CONSTRAINT MARCAPK PRIMARY KEY (IDMARCA)
);

CREATE TABLE LINEA(
IDLINEA INT NOT NULL AUTO_INCREMENT,
NOMBRELINEA VARCHAR (50) NOT NULL,
ESTADOLINEA INT NOT NULL,
CONSTRAINT LINEAPK PRIMARY KEY (IDLINEA)
);

CREATE TABLE BODEGA(
IDBODEGA INT NOT NULL AUTO_INCREMENT,
BODEGANOMBRE VARCHAR (50) NOT NULL,
ESTADOBODEGA INT NOT NULL,
CONSTRAINT BODEGAPK PRIMARY KEY (IDBODEGA)
);


CREATE TABLE PRODUCTO(
IDPRODUCTO INT NOT NULL AUTO_INCREMENT,
NOMBREPRODUCTO VARCHAR (50) NOT NULL,
PRODUCTORETEIVAID INT NOT NULL,
PRODUCTOMARCAID INT  NULL,
PRODUCTOLINEAID  INT NULL,
ESTADOPRODUCTO INT NOT NULL,
CONSTRAINT PRODUCTOPK PRIMARY KEY (IDPRODUCTO),
CONSTRAINT PRODUCTOFK1 FOREIGN KEY (PRODUCTORETEIVAID) REFERENCES RETEIVA (IDRETEIVA),
CONSTRAINT PRODUCTOFK2 FOREIGN KEY (PRODUCTOMARCAID) REFERENCES MARCA (IDMARCA),
CONSTRAINT PRODUCTOFK3 FOREIGN KEY (PRODUCTOLINEAID) REFERENCES LINEA (IDLINEA)
);


CREATE TABLE BODEGAPRODUCTO(
  PRODUCTOID INT NOT NULL PRIMARY KEY ,
  BODEGAID INT NOT NULL,
  BODEGAPRODUCTOENTRADA INT NULL ,
  BODEGAPRODUCTOSALIDA INT NULL ,
  BODEGAPRODUCTOTOTAL INT NULL ,
  CONSTRAINT BODEGAPRODUCTOFK1 FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTO (IDPRODUCTO),
  CONSTRAINT BODEGAPRODUCTOFK2 FOREIGN KEY (BODEGAID) REFERENCES BODEGA (IDBODEGA)
 );
 
CREATE TABLE INSUMO(
IDINSUMO INT NOT NULL AUTO_INCREMENT,
NOMBREINSUMO VARCHAR (50) NOT NULL,
INSUMOMARCAID INT NULL,
INSUMORETEIVAID INT NOT NULL,
INSUMOCANTIDADMINIMA INT NOT NULL,
INSUMOCANTIDADMAXIMA INT NOT NULL,
ESTADOINSUMO INT NOT NULL,
CONSTRAINT INSUMOPK PRIMARY KEY (IDINSUMO),
CONSTRAINT INSUMOFK2 FOREIGN KEY (INSUMOMARCAID) REFERENCES MARCA (IDMARCA),
CONSTRAINT INSUMOFK1 FOREIGN KEY (INSUMORETEIVAID) REFERENCES RETEIVA (IDRETEIVA)
);

CREATE TABLE BODEGAINSUMO(
  INSUMOID INT NOT NULL PRIMARY KEY ,
  BODEGAID INT NOT NULL,
  BODEGAINSUMOENTRADA INT NULL ,
  BODEGAINSUMOSALIDA INT NULL ,
  BODEGAINSUMOTOTAL INT NULL ,
  CONSTRAINT BODEGAINSUMOFK1 FOREIGN KEY (INSUMOID) REFERENCES INSUMO (IDINSUMO),
  CONSTRAINT BODEGAINSUMOFK2 FOREIGN KEY (BODEGAID) REFERENCES BODEGA (IDBODEGA)
 );

CREATE TABLE lISTAPRECIO(
IDLISTA INT NOT NULL AUTO_INCREMENT,
NOMBRELISTA VARCHAR (50) NOT NULL,
FIJAPRECIOLISTA VARCHAR (50) NULL,
CONSTRAINT lISTAPRECIOPK PRIMARY KEY (IDLISTA)
);

CREATE TABLE LISTAPRECIOPRODUCTO(
IDLISTAPRECIOPRODUCTO INT NOT NULL AUTO_INCREMENT,
LISTAID INT NOT NULL,
PRODUCTOID INT NOT NULL,
CONSTRAINT LISTAPRECIOPRODUCTOPK PRIMARY KEY (IDLISTAPRECIOPRODUCTO),
CONSTRAINT LISTAPRECIOPRODUCTOFK1 FOREIGN KEY (LISTAID) REFERENCES lISTAPRECIO (IDLISTA),
CONSTRAINT LISTAPRECIOPRODUCTOFK2 FOREIGN KEY (PRODUCTOID) REFERENCES PRODUCTO (IDPRODUCTO)
);

CREATE TABLE TERCERO(
IDTERCERO INT NOT NULL AUTO_INCREMENT,
TIPODOCUMENTO  VARCHAR (50) NOT NULL,
NUMERODOCUMENTO INT NOT NULL,
PRIMERNOMBRE VARCHAR (150) NOT NULL,
SEGUNDONOMBRE VARCHAR (150) NOT NULL,
PRIMERAPELLIDO VARCHAR (150) NOT NULL,
SEGUNDOAPELLIDO VARCHAR (150) NOT NULL,
CIUDADTERCERO INT NOT NULL,
TELEFONO VARCHAR (150) NOT NULL,
DIRECCION VARCHAR (150) NOT NULL,
CORREO VARCHAR (150) NOT NULL,
NOMBRECOMERCIAL VARCHAR (150) NULL,
REGIMENRENTA VARCHAR (150) NOT NULL,
TIPORETENCIONRENTAID INT NOT NULL,
REGIMENIVA VARCHAR (150) NOT NULL,
TARIFARETEIVA DOUBLE NOT NULL,
REGIMENICA VARCHAR (150) NOT NULL,
TIPORETENCIONICAID INT NOT NULL,
ESTADOTERCERO INT NOT NULL,
CONSTRAINT TERCEROPK PRIMARY KEY (IDTERCERO),
CONSTRAINT TERCEROFK1 FOREIGN KEY (CIUDADTERCERO) REFERENCES CIUDAD (IDCIUDAD),
CONSTRAINT TERCEROFK2 FOREIGN KEY (TIPORETENCIONRENTAID) REFERENCES RETENCIONRENTA (IDRETENCIONRENTA),
CONSTRAINT TERCEROFK3 FOREIGN KEY (TIPORETENCIONICAID) REFERENCES RETENCIONICA (IDRETENCIONICA)
);

CREATE TABLE PROVEEDOR(
IDPROVEEDOR INT NOT NULL AUTO_INCREMENT,
TERCEROID INT NOT NULL,
NOMBREREPRESENTANTE VARCHAR (50)  NULL,
APELLIDOREPRESENTANTE VARCHAR (50)  NULL,
TELEFONOPROVEEDOR VARCHAR (50)  NULL,
CIUDADID INT NOT NULL,
PLAZOPAGO INT NULL,
ESTADOPROVEEDOR INT NOT NULL,
CONSTRAINT PROVEEDORPK PRIMARY KEY (IDPROVEEDOR),
CONSTRAINT PROVEEDORFK1 FOREIGN KEY (TERCEROID) REFERENCES TERCERO (IDTERCERO),
CONSTRAINT PROVEEDORFK2 FOREIGN KEY (CIUDADID) REFERENCES CIUDAD (IDCIUDAD)
);


CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
TERCEROID INT NOT NULL,
NOMBREALMACEN VARCHAR (150) NULL,
CIUDADCLIENTE INT NOT NULL,
TELEFONO VARCHAR (150) NULL,
LISTAPRECIOID INT  NULL,
ESTADOCLIENTE INT NOT NULL,
CONSTRAINT CLIENTEPK PRIMARY KEY (IDCLIENTE),
CONSTRAINT CLIENTEFK1 FOREIGN KEY (TERCEROID) REFERENCES TERCERO (IDTERCERO),
CONSTRAINT CLIENTEFK2 FOREIGN KEY (CIUDADCLIENTE) REFERENCES CIUDAD (IDCIUDAD),
CONSTRAINT CLIENTEFK3 FOREIGN KEY (LISTAPRECIOID) REFERENCES lISTAPRECIO (IDLISTA)
);

CREATE TABLE ROL(
IDROL INT NOT NULL AUTO_INCREMENT,
NOMBREROL VARCHAR (50) NOT NULL,
ESTADOROL INT NOT NULL,
CONSTRAINT ROLPK PRIMARY KEY (IDROL)
);

CREATE TABLE USUARIO(
IDUSUARIO INT NOT NULL AUTO_INCREMENT,
TERCEROUSUARIO INT NOT NULL,
NOMBREUSUARIO VARCHAR (50) NOT NULL,
CONTRASENAUSUARIO VARCHAR (50) NOT NULL,
ESTADOUSUARIO INT NOT NULL,
CONSTRAINT USUARIOPK PRIMARY KEY (IDUSUARIO),
CONSTRAINT USUARIOFK1 FOREIGN KEY (TERCEROUSUARIO) REFERENCES TERCERO (IDTERCERO)
);

CREATE TABLE ROLUSUARIO (
IDROLUSUARIO INT NOT NULL,
USUARIOID INT NOT NULL,
ROLID INT NOT NULL,
CONSTRAINT ROLUSUARIOPK PRIMARY KEY (IDROLUSUARIO),
CONSTRAINT ROLUSUARIOFK1 FOREIGN KEY(USUARIOID) REFERENCES USUARIO(IDUSUARIO),
CONSTRAINT ROLUSUARIOFK2 FOREIGN KEY (ROLID) REFERENCES ROL (IDROL)
);

CREATE TABLE PERMISO (
IDPERMISOS INT NOT NULL AUTO_INCREMENT,
NOMBREPERMISO VARCHAR (50) NOT NULL,
URL TEXT NULL,
ICONO VARCHAR (50) NULL,
PERMISOP INT NULL,
CONSTRAINT PERMISOSPK PRIMARY KEY (IDPERMISOS),
CONSTRAINT PERMISOSFK FOREIGN KEY (PERMISOP) REFERENCES PERMISO (IDPERMISOS)
);

CREATE TABLE ROLPERMISO (
PERMISOID INT NOT NULL,
ROLPERMISOID INT NOT NULL,
ROLPID INT NOT NULL,
CONSTRAINT ROLPERMISOPK PRIMARY KEY (ROLPERMISOID),
CONSTRAINT ROLPERMISOFK1 FOREIGN KEY(PERMISOID) REFERENCES PERMISO(IDPERMISOS),
CONSTRAINT ROLPERMISOFK2 FOREIGN KEY (ROLPID) REFERENCES ROL (IDROL)
);


CREATE TABLE EMPLEADO(
IDEMPLEADO INT NOT NULL AUTO_INCREMENT,
CIUDADEXPEDICION  INT NOT NULL,
FECHAEXPEDICIONCEDULA DATE NOT NULL,
CIUDADNACIMIENTO  INT NOT NULL,
FECHANACIMIENTOEMPLEADO DATE NOT NULL,
NIVELEDUCACIONEMPLEADO VARCHAR (50) NOT NULL,
ESTADOCIVILEMPLEADO VARCHAR (50)   NOT NULL,
TERCEROIDEMPLEADO INT NOT NULL,
ESTADOEMPLEADO INT NOT NULL,
CONSTRAINT EMPLEADOPK PRIMARY KEY (IDEMPLEADO),
CONSTRAINT EMPLEADOFK1 FOREIGN KEY (CIUDADNACIMIENTO) REFERENCES CIUDAD(IDCIUDAD),
CONSTRAINT EMPLEADOFK2 FOREIGN KEY (CIUDADEXPEDICION) REFERENCES CIUDAD(IDCIUDAD),
CONSTRAINT EMPLEADOFK3 FOREIGN KEY (TERCEROIDEMPLEADO) REFERENCES TERCERO (IDTERCERO)
);


CREATE TABLE COTIZACION(
IDCOTIZACION INT NOT NULL AUTO_INCREMENT,
FECHACREACIONCOTIZACION DATE NOT NULL,
PROVEEDORID INT NOT NULL,
CONSTRAINT COTIZACIONPK PRIMARY KEY (IDCOTIZACION),
CONSTRAINT COTIZACIONFK FOREIGN KEY(PROVEEDORID) REFERENCES PROVEEDOR(IDPROVEEDOR)
);

CREATE TABLE DETALLECOTIZACION(
IDDETALLECOTIZACION  INT NOT NULL AUTO_INCREMENT,
COTIZACIONID INT NOT NULL,
INSUMOID INT NOT NULL,
PRECIO DOUBLE NOT NULL,
CANTIDA INT NOT NULL,
CONSTRAINT DETALLECOTIZACIONPK PRIMARY KEY (IDDETALLECOTIZACION) ,
CONSTRAINT DETALLECOTIZACIONFK1 FOREIGN KEY (COTIZACIONID) REFERENCES COTIZACION(IDCOTIZACION),
CONSTRAINT DETALLECOTIZACIONFK2 FOREIGN KEY (INSUMOID) REFERENCES INSUMO(IDINSUMO)
);

CREATE TABLE COMPRA(
IDCOMPRA INT NOT NULL AUTO_INCREMENT,
FECHACREACIONCOMPRA DATE NOT NULL,
COTIZACIONID INT NOT NULL,
CONSTRAINT COMPRAPK PRIMARY KEY (IDCOMPRA),
CONSTRAINT COMPRAFK1 FOREIGN KEY (COTIZACIONID) REFERENCES COTIZACION(IDCOTIZACION)
);

CREATE TABLE DETALLECOMPRA(
IDDETALLECOMPRA INT NOT NULL AUTO_INCREMENT,
COMPRAID INT NOT NULL,
INSUMOID INT NOT NULL,
BODEGAID INT NOT NULL,
PRECIO DOUBLE NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT DETALLECOMPRAPK PRIMARY KEY (IDDETALLECOMPRA) ,
CONSTRAINT DETALLECOMPRAFK1 FOREIGN KEY (COMPRAID) REFERENCES COMPRA(IDCOMPRA),
CONSTRAINT DETALLECOMPRAFK2 FOREIGN KEY (BODEGAID) REFERENCES BODEGA(IDBODEGA),
CONSTRAINT DETALLECOMPRAFK3 FOREIGN KEY (INSUMOID) REFERENCES INSUMO(IDINSUMO)
);


CREATE TABLE MOVIMIENTOINVENTARIO(
IDMOVIMIENTO INT NOT NULL AUTO_INCREMENT,
FUENTE VARCHAR (10) NOT NULL,
DESCRIPCION VARCHAR (100),
FECHAMOVIMIENTO DATE NOT NULL,
NOTAS VARCHAR (100) ,
ESTADO  INT NOT NULL,
BODEGAID INT NOT NULL,
BODEGADESTINOID INT,
CONSTRAINT MOVIMIENTOPK PRIMARY KEY (IDMOVIMIENTO),
CONSTRAINT MOVIMIENTOFK FOREIGN KEY (BODEGAID) REFERENCES BODEGA(IDBODEGA),
CONSTRAINT MOVIMIENTOFK2 FOREIGN KEY (BODEGADESTINOID) REFERENCES BODEGA(IDBODEGA)
);

CREATE TABLE DETALLEMOVIMIENTO(
IDMOVIMIENTODETALLE INT NOT NULL AUTO_INCREMENT,
MOVIMIENTOID INT NOT NULL,
INSUMOID INT NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT DETALLEMOVIMIENTOPK PRIMARY KEY (IDMOVIMIENTODETALLE ),
CONSTRAINT DETALLEMOVIMIENTOFK FOREIGN KEY (MOVIMIENTOID) REFERENCES MOVIMIENTOINVENTARIO(IDMOVIMIENTO),
CONSTRAINT DETALLEMOVIMIENTOFK2 FOREIGN KEY (INSUMOID) REFERENCES INSUMO(IDINSUMO)
);



CREATE TABLE CONTRATOEMPLEADO(
IDCONTRATO INT NOT NULL AUTO_INCREMENT,
EMPLEADOID INT NOT NULL,
TIPOCONTRATO VARCHAR (50) NOT NULL,
PERIODOPAGO VARCHAR (15) NOT NULL,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
PERIODOPRUEBA INT NOT NULL,
CIUDADTRABAJO INT NOT NULL,
CODIGOCARGO INT NOT NULL,
CODIGOSECCION INT NOT NULL,
SALARIOINICIAL DOUBLE NOT NULL,
SALARIOACTUAL DOUBLE NOT NULL,
CODIGOEPS INT NOT NULL,
CODIGOARL INT NOT NULL,
CODIGOCAJA INT NOT NULL,
CODIGOPENSIONES INT NOT NULL,
CODIGOCESANTIAS INT NOT NULL,
ESTADOCONTRATOEMPLEADO INT NOT NULL,
CONSTRAINT CONTRATOPK PRIMARY KEY (IDCONTRATO),
CONSTRAINT CONTRATOFK1 FOREIGN KEY (EMPLEADOID) REFERENCES EMPLEADO(IDEMPLEADO),
CONSTRAINT CONTRATOFK2 FOREIGN KEY (CIUDADTRABAJO) REFERENCES CIUDAD(IDCIUDAD),
CONSTRAINT CONTRATOFK3 FOREIGN KEY (CODIGOCARGO) REFERENCES CARGO(IDCARGO),
CONSTRAINT CONTRATOFK4 FOREIGN KEY (CODIGOSECCION) REFERENCES SECCION(IDSECCION),
CONSTRAINT CONTRATOFK5 FOREIGN KEY (CODIGOEPS) REFERENCES entidadseguridad (IDENTIDAD),
CONSTRAINT CONTRATOFK6 FOREIGN KEY (CODIGOARL) REFERENCES entidadseguridad (IDENTIDAD),
CONSTRAINT CONTRATOFK7 FOREIGN KEY (CODIGOCAJA) REFERENCES entidadseguridad (IDENTIDAD),
CONSTRAINT CONTRATOFK8 FOREIGN KEY (CODIGOPENSIONES) REFERENCES entidadseguridad (IDENTIDAD),
CONSTRAINT CONTRATOFK9 FOREIGN KEY (CODIGOCESANTIAS) REFERENCES entidadseguridad (IDENTIDAD)
);

CREATE TABLE VACACIONEMPLEADO(
IDVACACION INT NOT NULL AUTO_INCREMENT,
EMPLEADOID INT NOT NULL,
FECHAINICIO DATE NOT NULL,
FECHAFIN DATE NOT NULL,
DIASPAGOS INT NOT NULL,
DESCUENTOSLEY DOUBLE NOT NULL,
OTROSDESUENTOS DOUBLE,
TOTALPAGO DOUBLE NOT NULL,
CONSTRAINT VACACIONPK PRIMARY KEY (IDVACACION),
CONSTRAINT VACACIONFK FOREIGN KEY (EMPLEADOID) REFERENCES EMPLEADO(IDEMPLEADO)
);

INSERT INTO `mediussoftware`.`ciudad` (`IDCIUDAD`, `NUMEROCIUDAD`, `CIUDADNOMBRE`) VALUES ('1', '123', 'BOGOTA');
INSERT INTO `mediussoftware`.`reteiva` (`IDRETEIVA`, `NOMBRERETEIVA`, `TASARETEIVA`) VALUES ('1', 'IVA', '34');
INSERT INTO `mediussoftware`.`retencionica` (`IDRETENCIONICA`, `NOMBRERETENCIONICA`, `TASARETENCIONICA`, `UVTRETENCIONICA`, `ESTADORETENCIONICA`) VALUES ('1', 'ICA', '12', '12', '1');
INSERT INTO `mediussoftware`.`retencionrenta` (`IDRETENCIONRENTA`, `NOMBRERETENCIONRENTA`, `TASARETENCIONRENTA`, `UVTRETENCIONRENTA`, `ESTADORETENCIONRENTA`) VALUES ('1', 'RENTA', '12', '12', '1');
INSERT INTO `mediussoftware`.`tercero` (`IDTERCERO`, `TIPODOCUMENTO`, `NUMERODOCUMENTO`, `PRIMERNOMBRE`, `SEGUNDONOMBRE`, `PRIMERAPELLIDO`, `SEGUNDOAPELLIDO`, `CIUDADTERCERO`, `TELEFONO`, `DIRECCION`, `CORREO`, `NOMBRECOMERCIAL`, `REGIMENRENTA`, `TIPORETENCIONRENTAID`, `REGIMENIVA`, `TARIFARETEIVA`, `REGIMENICA`, `TIPORETENCIONICAID`, `ESTADOTERCERO`) VALUES ('1', 'cc', '10779670009', 'oscar', 'andres', 'aguirre', 'ducuara', '1', '123', '1eedf', 'gvhjv', 'vfhjvj', '1', '1', '1', '1', '1', '1', '1');
INSERT INTO `mediussoftware`.`usuario` (`IDUSUARIO`, `TERCEROUSUARIO`, `NOMBREUSUARIO`, `CONTRASENAUSUARIO`, `ESTADOUSUARIO`) VALUES ('1', '1', 'oscar', '123', '1');
INSERT INTO `mediussoftware`.`marca` (`IDMARCA`, `NOMBREMARCA`, `ESTADOMARCA`) VALUES ('1', 'doria', '1');
INSERT INTO `mediussoftware`.`linea` (`IDLINEA`, `NOMBRELINEA`, `ESTADOLINEA`) VALUES ('1', 'No aplica', '1');
INSERT INTO `mediussoftware`.`bodega` (`IDBODEGA`, `BODEGANOMBRE`, `ESTADOBODEGA`) VALUES ('1', 'BODEGA1', '1');
INSERT INTO `mediussoftware`.`insumo` (`IDINSUMO`, `NOMBREINSUMO`, `INSUMOMARCAID`, `INSUMORETEIVAID`, `INSUMOCANTIDADMINIMA`, `INSUMOCANTIDADMAXIMA`, `ESTADOINSUMO`) VALUES ('1', 'PAPAS FRITAS', '1', '1', '5', '12', '1');
INSERT INTO `mediussoftware`.`bodegainsumo` (`INSUMOID`, `BODEGAID`, `BODEGAINSUMOENTRADA`, `BODEGAINSUMOSALIDA`, `BODEGAINSUMOTOTAL`) VALUES ('1', '1', '6', '3', '3');


select ins.nombreinsumo, bd.bodeganombre, dbi.bodegainsumototal
from bodegainsumo dbi
inner join insumo ins on  dbi.insumoid=ins.idinsumo
inner join bodega bd on dbi.bodegaid=bd.idbodega where dbi.bodegainsumototal<ins.insumocantidadminima;




